# Generated by Django 6.0.7 on 2026-07-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_user_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='submission_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeetask',
            name='work_submission',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
